/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exert.antlr;

public class App {
    public String getGreeting() {
        return "Exert Antlr";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
